### ISSUE TITLE
Wrong narration in angular beginner's course and completely skips some sections

### ISSUE THREAD

**Issue by jforjava1981** [angular-university/angular-course#4]
Angular's beginners course lesson - injectable services describes the course as angular deep dive course. Also the previous lesson has the course card component developed but not the course-image component. it doesn't describe how to do that and directly skips to a lesson where we see course-image component in the template. Even though learned developers will know how it works and how it came there there has to be some explaination. 
Please remember we This is a paid course and as paid users we want flawless experience. 
1) so code and description in the video doesnt match.
2) narration talks about altogether different course
3) no mention of some sections. 
4) also in previous to previous lesson ends with comment that we will learn ng-container which never is described in this course.?
Why so much errors?

**Comment by jhades** [comment]
Hello, what happens is that the beginners course which is a free course is a subset of the deep dive course. I think the simplest is to get the deep dive course to get the whole material,  the beginners course was created to focus on the most commonly used subset of angular, but this was decided after filming the deep dive course.
